extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  attributes/remove-sensitive-url-data:
    actions:
      - key: url.full
        action: delete
      - key: http.url
        action: delete
      - key: http.target
        action: delete
  batch:

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes/remove-sensitive-url-data, batch]
      exporters: [otlp/jaeger]
